### PR TITLE
change build.fsx file mode / fix permission issue

### PR DESCRIPTION
**Pull request by Heather**
let try this way `100644 → 100755`

### CODE REVIEW

**Comment by Heather** [comment]
strange... there another error however build.fsx works fine locally for me

**Comment by Heather** [comment]
trying to update travis

**Comment by Heather** [comment]
`Compatibility.fs(72,28): error FS0407: The mutable variable 'last' is used in an invalid way. Mutable variables cannot be captured by closures.` - still being old F# version?

**Comment by Heather** [comment]
phew

```
	 2 Warning(s)
	 0 Error(s)
```

**Comment by gmpl** [comment]
Thanks. I will have a look later when back home.

**Comment by gmpl** [comment]
Works fine, thanks again. Will see if I can do the same for FsControl.

**Comment by Heather** [comment]
@gmpl you're welcome :+1:

**Comment by gmpl** [comment]
I tried also with FsControl but [there](https://github.com/gmpl/FsControl/commit/444d48a86e087fa88aae2a9ded9e3991d5bd0753) I'm getting: "./build.fsx: Permission denied". Is it the same problem? I copied the latest files with your fix.

**Comment by Heather** [comment]
@gmpl looks like =)

**Comment by Heather** [comment]
https://github.com/gmpl/FsControl/pull/58 - here is correction

**Pull request merged**
